import React from "react";
import { Line } from "@ant-design/plots";
import Head from 'next/head'

const DemoLine = () => {
  const data = [
    {
      year: "1991",
      value: 3,
      data : 3
    },
    {
      year: "1992",
      value: 4,
      data : 3
    },
    {
      year: "1993",
      value: 3.5,
      data : 3
    },
    {
      year: "1994",
      value: 5,
      data : 3
    },
    {
      year: "1995",
      value: 4.9,
      data : 3
    },
    {
      year: "1996",
      value: 6,
      data : 3
    },
    {
      year: "1997",
      value: 7,
      data : 3
    },
    {
      year: "1998",
      value: 9,
      data : 3
    },
    {
      year: "1999",
      value: 13,
      data : 3
    }
  ];

  const config = {
    data,
    xField: "year",
    yField: "value",
    zField: "data",
    label: {},
    point: {
      size: 5,
      shape: "circle",
      style: {
        fill: "red",
        stroke: "lime",
        lineWidth: 5
      }
    },
    tooltip: {
      showMarkers: true
    },
    state: {
      active: {
        style: {
          shadowBlur: 4,
          stroke: "#000",
          fill: "red"
        }
      }
    },
    interactions: [
      {
        type: "marker-active"
      }
    ]
  };
  return (<>
    <Head>
        <title>Ant Demo Line</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Line {...config} />
  </>
  
  )
  ;
};

export default DemoLine;
